export const busy = [
    "Eae, eu to ocupada agora. Logo mais eu volto.",
    "Oi, eu to ocupada agora. Logo mais eu volto.",
    "Beleza. Olha, agora não da pra eu te ajudar. Logo mais eu volto.",
    "Fala, olha eu to ocupada agora, mas mais tarde eu volto.",
    "Oi! No momento to ocupada, mas depois a gente se fala.",
    "Agora não rola, to ocupada. Depois a gente conversa!",
    "To enrolada agora, mas daqui a pouco eu volto.",
    "Tô numa correria agora, te chamo depois!",
    "Agora to sem tempo, mas daqui a pouco eu volto.",
    "To ocupada por enquanto, mais tarde a gente conversa!",
    "Rapidão, to ocupada agora. Depois a gente se fala!",
    "Agora não dá, mas te respondo assim que puder!",
    "To cheia de coisa pra fazer agora, depois eu volto!",
    "No momento to ocupada, mas já já to de volta!",
];