import { afterEach, expect, it, vi } from "vitest";
import { BackgroundLoop } from "@/app/BackgroundLoop";
afterEach(() => vi.useRealTimers());
it("does not overlap callbacks or reschedule an in-flight callback after stop", async () => {
    vi.useFakeTimers();
    const loop = new BackgroundLoop();
    let finish!: () => void;
    const work = vi.fn(() => new Promise<void>(resolve => { finish = resolve; }));
    loop.start(work, () => 10, vi.fn());
    loop.start(work, () => 10, vi.fn());
    await vi.advanceTimersByTimeAsync(10);
    expect(work).toHaveBeenCalledOnce();
    await vi.advanceTimersByTimeAsync(100);
    expect(work).toHaveBeenCalledOnce();
    loop.stop();
    const resumed = vi.fn().mockResolvedValue(undefined);
    loop.start(resumed, () => 10, vi.fn());
    await vi.advanceTimersByTimeAsync(20);
    expect(resumed).not.toHaveBeenCalled();
    loop.stop();
    finish();
    await vi.advanceTimersByTimeAsync(100);
    expect(vi.getTimerCount()).toBe(0);
    const next = vi.fn().mockResolvedValue(undefined);
    loop.start(next, () => 10, vi.fn());
    await vi.advanceTimersByTimeAsync(10);
    expect(next).toHaveBeenCalledOnce();
    loop.stop();
});
